language: python
python:
  - "3.7"
  -
install:
  - pip install -r requirements.txt

services: 
  - mongodb

before_script:
  - sleep 15
  - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'

script:
  - cd RouleMaPoule
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py test