language: python
python:
  - "3.7"
  -
# command to install dependencies
install:
 - pip install -r requirements.txt
script:
 - cd /RouleMaPoule
 - python manage.py makemigrations
 - python manage.py migrate
 - python manage.py test